version: '3'

services:
  bootcampservice:
    build: ./logs-shipper
    deploy:
      replicas: ${REPLICAS}
    volumes:
      - ./inf/build/resources/main/elasticsearch.config:/usr/bootcamp/resources/main/elasticsearch.config
      - ./inf/build/resources/main/server.config:/usr/bootcamp/resources/main/server.config

  load-balancer-service:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 8000:${PORT}
    environment:
      - REPLICAS=${REPLICAS}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  indexer:
    build: ./indexer

